services:
  ramp-api:
    build: .
    image: ghcr.io/${GITHUB_REPOSITORY,,}:latest
    ports:
      - "8000:8000"
    volumes:
      - "./weights:/app/weights"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
